#ifndef WATCH_AI_APP_CONFIG_H
#define WATCH_AI_APP_CONFIG_H

#include <stdint.h>

#include "app_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WATCH_AI_PRODUCT_NAME "ec718-watch-ai"
#define WATCH_AI_PROTOCOL_TYPE APP_PROTOCOL_TYPE_APP_AI_WS

#define WATCH_AI_WS_ENDPOINT ""
#define WATCH_AI_WS_TOKEN ""
#define WATCH_AI_DEVICE_ID "ec718-device"
#define WATCH_AI_CLIENT_ID "ec718-client"
#define WATCH_AI_MODEL "ec718"

#define WATCH_AI_AUDIO_SAMPLE_RATE_HZ 16000U
#define WATCH_AI_AUDIO_FRAME_MS 20U
#define WATCH_AI_AUDIO_FRAME_SAMPLES 320U
#define WATCH_AI_AUDIO_MAX_ENCODED_BYTES 256U

#define WATCH_AI_ENABLE_DISPLAY 1
#define WATCH_AI_ENABLE_MEDIA 0
#define WATCH_AI_ENABLE_NETWORK 0
#define WATCH_AI_ENABLE_PROTOCOL 0
#define WATCH_AI_ENABLE_TOOL 0
#define WATCH_AI_ENABLE_CAMERA 1
#define WATCH_AI_ENABLE_SCAN 1
#define WATCH_AI_ENABLE_TTS 1
#ifndef WATCH_AI_ENABLE_GIF
#define WATCH_AI_ENABLE_GIF 0
#endif
#define WATCH_AI_ENABLE_LWS_TRANSPORT 0
#define WATCH_AI_ENABLE_LIOT_AUDIO_PORT 0
#define WATCH_AI_ENABLE_LIOT_CAMERA_PORT 1
#define WATCH_AI_ENABLE_LIOT_SCAN_PORT 1
#define WATCH_AI_ENABLE_LVGL_DISPLAY_PORT 1
#define WATCH_AI_DISPLAY_LVGL_TICK_MS 1U
#define WATCH_AI_DISPLAY_LVGL_HANDLER_MS 10U
#define WATCH_AI_DISPLAY_LVGL_QUEUE_DEPTH 10U
#define WATCH_AI_DISPLAY_LVGL_DRAW_BUF_ROWS 20U

#ifdef __cplusplus
}
#endif

#endif /* WATCH_AI_APP_CONFIG_H */
