#ifndef APP_TYPES_H
#define APP_TYPES_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    APP_PROTOCOL_TYPE_NONE = 0,
    APP_PROTOCOL_TYPE_APP_AI_WS,
    APP_PROTOCOL_TYPE_APP_AI_MQTT_UDP,
    APP_PROTOCOL_TYPE_COZE_WS,
    APP_PROTOCOL_TYPE_COMPANY_PRIVATE,
} app_protocol_type_t;

typedef enum {
    APP_EV_NONE = 0,
    APP_EV_BOOT_DONE,
    APP_EV_NETWORK_CONNECTED,
    APP_EV_NETWORK_DISCONNECTED,
    APP_EV_PROTOCOL_CONNECTED,
    APP_EV_PROTOCOL_DISCONNECTED,
    APP_EV_CAMERA_START,
    APP_EV_CAMERA_STOP,
    APP_EV_CAMERA_ERROR,
    APP_EV_SCAN_START,
    APP_EV_SCAN_STOP,
    APP_EV_SCAN_RESULT,
    APP_EV_AUDIO_SEND_READY,
    APP_EV_AUDIO_RECV,
    APP_EV_WAKEUP,
    APP_EV_VAD_START,
    APP_EV_VAD_END,
    APP_EV_BUTTON_PRESS,
    APP_EV_TOUCH_ACTION,
    APP_EV_DISPLAY_ACTION,
    APP_EV_RECORDER_DONE,
    APP_EV_OTA_PROGRESS,
    APP_EV_ERROR,
    APP_EV_SHUTDOWN,
} app_event_id_t;

typedef enum {
    APP_STATE_BOOTING = 0,
    APP_STATE_IDLE,
    APP_STATE_CONNECTING,
    APP_STATE_CAMERA,
    APP_STATE_SCAN,
    APP_STATE_LISTENING,
    APP_STATE_THINKING,
    APP_STATE_SPEAKING,
    APP_STATE_ACTIVATING,
    APP_STATE_UPGRADING,
    APP_STATE_SLEEP,
    APP_STATE_ERROR,
    APP_STATE_SHUTDOWN,
    APP_STATE_MAX,
} app_state_t;

typedef enum {
    APP_POWER_MODE_LOW_POWER = 0,
    APP_POWER_MODE_BALANCED,
    APP_POWER_MODE_PERFORMANCE,
} app_power_mode_t;

typedef enum {
    APP_RECORDER_STOP_REASON_NONE = 0,
    APP_RECORDER_STOP_REASON_NORMAL,
    APP_RECORDER_STOP_REASON_NO_SPACE,
    APP_RECORDER_STOP_REASON_ERROR,
} app_recorder_stop_reason_t;

#ifdef __cplusplus
}
#endif

#endif /* APP_TYPES_H */
