#ifndef BAJI_PHOTO_CONFIG_H
#define BAJI_PHOTO_CONFIG_H

#define BAJI_PHOTO_BUILTIN_COUNT        5u
#define BAJI_PHOTO_DL_MAX               20u
#define BAJI_PHOTO_TOTAL_MAX            (BAJI_PHOTO_BUILTIN_COUNT + BAJI_PHOTO_DL_MAX)

#ifndef BAJI_PHOTO_ENABLE_BUILTIN_DISPLAY
#define BAJI_PHOTO_ENABLE_BUILTIN_DISPLAY 0
#endif

#ifndef BAJI_PHOTO_LINK_BUILTIN_ASSETS
#define BAJI_PHOTO_LINK_BUILTIN_ASSETS    0
#endif

#ifndef BAJI_PHOTO_ENABLE_GIF_SUPPORT
#define BAJI_PHOTO_ENABLE_GIF_SUPPORT     1
#endif

#ifndef BAJI_PHOTO_ENABLE_JPEG_SUPPORT
#define BAJI_PHOTO_ENABLE_JPEG_SUPPORT    0
#endif

#ifndef BAJI_PHOTO_ENABLE_PNG_SUPPORT
#define BAJI_PHOTO_ENABLE_PNG_SUPPORT     0
#endif

#ifndef BAJI_PHOTO_JPEG_MAX_COMPRESSED_SIZE
#define BAJI_PHOTO_JPEG_MAX_COMPRESSED_SIZE 0u
#endif

#ifndef BAJI_PHOTO_PNG_MAX_COMPRESSED_SIZE
#define BAJI_PHOTO_PNG_MAX_COMPRESSED_SIZE 0u
#endif

#ifndef BAJI_PHOTO_PNG_VENDOR_BACKEND_READY
#define BAJI_PHOTO_PNG_VENDOR_BACKEND_READY 0
#endif

#ifndef BAJI_PHOTO_GIF_PLAYER_GIFD
#define BAJI_PHOTO_GIF_PLAYER_GIFD        1
#endif

#ifndef BAJI_PHOTO_ENABLE_DEBUG_FLASH_ARTIFACTS
#define BAJI_PHOTO_ENABLE_DEBUG_FLASH_ARTIFACTS 0
#endif

#ifndef BAJI_PHOTO_HTTP_RAW_RGB565_VERIFY
#define BAJI_PHOTO_HTTP_RAW_RGB565_VERIFY 0
#endif

#ifndef BAJI_PHOTO_ENABLE_PLAYBACK_META_PERSIST
#define BAJI_PHOTO_ENABLE_PLAYBACK_META_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_STORE_INVENTORY_DIAG
#define BAJI_PHOTO_ENABLE_STORE_INVENTORY_DIAG 0
#endif

#ifndef BAJI_PHOTO_ENABLE_INDEX_READBACK_DIAG
#define BAJI_PHOTO_ENABLE_INDEX_READBACK_DIAG 0
#endif

#ifndef BAJI_PHOTO_ENABLE_PENDING_REPLY_ATTEMPT_PERSIST
#define BAJI_PHOTO_ENABLE_PENDING_REPLY_ATTEMPT_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_ACCEPTED_SENT_PERSIST
#define BAJI_PHOTO_ENABLE_ACCEPTED_SENT_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_HTTP_RETRY_COUNT_PERSIST
#define BAJI_PHOTO_ENABLE_HTTP_RETRY_COUNT_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_NETWORK_WAIT_STATE_PERSIST
#define BAJI_PHOTO_ENABLE_NETWORK_WAIT_STATE_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_DISPLAY_RESULT_STATE_PERSIST
#define BAJI_PHOTO_ENABLE_DISPLAY_RESULT_STATE_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_NON_RANGE_TASK_CHECKPOINT_PERSIST
#define BAJI_PHOTO_ENABLE_NON_RANGE_TASK_CHECKPOINT_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_NON_RANGE_TASK_READY_PERSIST
#define BAJI_PHOTO_ENABLE_NON_RANGE_TASK_READY_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_NON_RANGE_TASK_RESTART_PERSIST
#define BAJI_PHOTO_ENABLE_NON_RANGE_TASK_RESTART_PERSIST 0
#endif

#ifndef BAJI_PHOTO_ENABLE_FLASH_WRITE_DEDUP
#define BAJI_PHOTO_ENABLE_FLASH_WRITE_DEDUP 1
#endif

#ifndef BAJI_PHOTO_TASK_STATE_CHECKPOINT_BYTES
#define BAJI_PHOTO_TASK_STATE_CHECKPOINT_BYTES (64u * 1024u)
#endif

#ifndef BAJI_PHOTO_TASK_STATE_CHECKPOINT_PERCENT
#define BAJI_PHOTO_TASK_STATE_CHECKPOINT_PERCENT 5u
#endif

#ifndef APP_BUILD_GIT_SHORT
#define APP_BUILD_GIT_SHORT "unknown"
#endif

#ifndef APP_BUILD_PROJECT
#define APP_BUILD_PROJECT "unknown"
#endif

#ifndef APP_BUILD_MODE
#define APP_BUILD_MODE "unknown"
#endif

#ifndef APP_BUILD_TIMESTAMP
#define APP_BUILD_TIMESTAMP __DATE__ " " __TIME__
#endif

#ifndef BAJI_PHOTO_BUILD_GIT_SHORT
#define BAJI_PHOTO_BUILD_GIT_SHORT APP_BUILD_GIT_SHORT
#endif

#ifndef BAJI_PHOTO_BUILD_PROJECT
#define BAJI_PHOTO_BUILD_PROJECT APP_BUILD_PROJECT
#endif

#ifndef BAJI_PHOTO_BUILD_MODE
#define BAJI_PHOTO_BUILD_MODE APP_BUILD_MODE
#endif

#ifndef BAJI_PHOTO_BUILD_TIMESTAMP
#define BAJI_PHOTO_BUILD_TIMESTAMP APP_BUILD_TIMESTAMP
#endif

#define BAJI_PHOTO_HTTP_RAW_RGB565_ID      "live_rgb565_001"
#define BAJI_PHOTO_HTTP_RAW_RGB565_NAME    "live rgb565 verify"
#define BAJI_PHOTO_HTTP_RAW_RGB565_PATH    "badge/api/image/img_126334eb19b14e01"
#define BAJI_PHOTO_HTTP_RAW_RGB565_URL     "http://ai.iwg.senthink.com/badge/api/image/img_126334eb19b14e01"
#define BAJI_PHOTO_HTTP_RAW_RGB565_W       360u
#define BAJI_PHOTO_HTTP_RAW_RGB565_H       360u
#define BAJI_PHOTO_HTTP_RAW_RGB565_SIZE    (BAJI_PHOTO_HTTP_RAW_RGB565_W * BAJI_PHOTO_HTTP_RAW_RGB565_H * BAJI_PHOTO_IMG_BPP)

#if BAJI_PHOTO_ENABLE_BUILTIN_DISPLAY && !BAJI_PHOTO_LINK_BUILTIN_ASSETS
#error "BAJI_PHOTO_ENABLE_BUILTIN_DISPLAY requires BAJI_PHOTO_LINK_BUILTIN_ASSETS"
#endif

#if BAJI_PHOTO_ENABLE_JPEG_SUPPORT && (BAJI_PHOTO_JPEG_MAX_COMPRESSED_SIZE == 0u)
#error "BAJI_PHOTO_ENABLE_JPEG_SUPPORT requires BAJI_PHOTO_JPEG_MAX_COMPRESSED_SIZE > 0"
#endif

#if BAJI_PHOTO_ENABLE_PNG_SUPPORT && (BAJI_PHOTO_PNG_MAX_COMPRESSED_SIZE == 0u)
#error "BAJI_PHOTO_ENABLE_PNG_SUPPORT requires BAJI_PHOTO_PNG_MAX_COMPRESSED_SIZE > 0"
#endif

#if BAJI_PHOTO_ENABLE_PNG_SUPPORT && !BAJI_PHOTO_PNG_VENDOR_BACKEND_READY
#error "BAJI_PHOTO_ENABLE_PNG_SUPPORT is blocked until the F9D_A vendor PNG backend symbols are qualified and enabled"
#endif

#define BAJI_PHOTO_IMG_W                360u
#define BAJI_PHOTO_IMG_H                360u
#define BAJI_PHOTO_IMG_BPP              2u
#define BAJI_PHOTO_IMG_DATA_SIZE        (BAJI_PHOTO_IMG_W * BAJI_PHOTO_IMG_H * BAJI_PHOTO_IMG_BPP)

#define BAJI_PHOTO_MAGIC                0x424A5048u
#define BAJI_PHOTO_ID_MAX_LEN           32u
#define BAJI_PHOTO_NAME_MAX_LEN         48u
#define BAJI_PHOTO_PATH_MAX_LEN         160u

#ifndef BAJI_PHOTO_ENABLE_MQTT_CONTROL
#define BAJI_PHOTO_ENABLE_MQTT_CONTROL  1
#endif

#ifndef BAJI_PHOTO_MQTT_BROKER_URL
#define BAJI_PHOTO_MQTT_BROKER_URL      "mqtt://39.100.94.55:51883"
#endif

#ifndef BAJI_PHOTO_MQTT_PASSWORD
#define BAJI_PHOTO_MQTT_PASSWORD        "BAJI_PRODUCT_SECRET_PLACEHOLDER"
#endif

#ifndef BAJI_PHOTO_MQTT_USE_FIXED_DEVICE_ID
#define BAJI_PHOTO_MQTT_USE_FIXED_DEVICE_ID 0
#endif

#ifndef BAJI_PHOTO_MQTT_FIXED_DEVICE_ID
#define BAJI_PHOTO_MQTT_FIXED_DEVICE_ID "868001234567890"
#endif

#ifndef BAJI_PHOTO_MQTT_USE_PLAIN_CLIENT_ID
#define BAJI_PHOTO_MQTT_USE_PLAIN_CLIENT_ID 1
#endif

#define BAJI_PHOTO_MQTT_CLIENT_ID_PREFIX "badge_"
#define BAJI_PHOTO_MQTT_CLIENT_ID_MAX   24u
#define BAJI_PHOTO_MQTT_TOPIC_MAX       80u
#define BAJI_PHOTO_MQTT_TX_BUF_MAX      768u
#define BAJI_PHOTO_MQTT_RX_BUF_MAX      1536u
#define BAJI_PHOTO_MQTT_KEEPALIVE_S     30u
#define BAJI_PHOTO_MQTT_PING_TIMEOUT_S  5u
#define BAJI_PHOTO_MQTT_DELIVERY_TIME_S 5u
#define BAJI_PHOTO_MQTT_DELIVERY_CNT    3u
#define BAJI_PHOTO_MQTT_QOS             1u
#define BAJI_PHOTO_MQTT_CLEAN_SESSION   0u
#define BAJI_PHOTO_MQTT_TASK_STACK      16384u
#define BAJI_PHOTO_MQTT_TASK_PRIO       4u
#define BAJI_PHOTO_MQTT_CONNECT_WAIT_MS 15000u
#ifndef BAJI_PHOTO_MQTT_ONLINE_DYNAMIC_DEVICE_INFO
#define BAJI_PHOTO_MQTT_ONLINE_DYNAMIC_DEVICE_INFO 0
#endif
#ifndef BAJI_PHOTO_MQTT_STATUS_DYNAMIC_TIMESTAMP
#define BAJI_PHOTO_MQTT_STATUS_DYNAMIC_TIMESTAMP 0
#endif
#ifndef BAJI_PHOTO_MQTT_ONLINE_FIRMWARE_VERSION
#define BAJI_PHOTO_MQTT_ONLINE_FIRMWARE_VERSION "dev-x"
#endif
#ifndef BAJI_PHOTO_MQTT_ONLINE_HARDWARE_VERSION
#define BAJI_PHOTO_MQTT_ONLINE_HARDWARE_VERSION "A1"
#endif
#ifndef BAJI_PHOTO_MQTT_START_DELAY_MS
#define BAJI_PHOTO_MQTT_START_DELAY_MS 5000u
#endif
#define BAJI_PHOTO_MQTT_HEARTBEAT_DEFAULT_S 30u
#define BAJI_PHOTO_MQTT_RECONNECT_MIN_S 2u
#define BAJI_PHOTO_MQTT_RECONNECT_MAX_S 60u
#define BAJI_PHOTO_BIND_TOKEN_REFRESH_LEAD_S 10u
#define BAJI_PHOTO_BIND_TOKEN_RETRY_S   15u
#define BAJI_PHOTO_RANGE_CHUNK_DEFAULT 4096u
#define BAJI_PHOTO_RANGE_CHUNK_MAX     8192u
#define BAJI_PHOTO_RANGE_FAIL_MAX      5u
#define BAJI_PHOTO_RANGE_VERIFY_BUF_SIZE 4096u
#define BAJI_PHOTO_MQTT_REASON_MAX_LEN 95u

#define BAJI_PHOTO_TASK_ID_MAX_LEN      48u
#define BAJI_PHOTO_IMAGE_ID_MAX_LEN     BAJI_PHOTO_ID_MAX_LEN
#define BAJI_PHOTO_PLAY_TRIGGER_MAX_LEN 24u
#define BAJI_PHOTO_IMAGE_URL_MAX_LEN    256u
#define BAJI_PHOTO_IMAGE_MD5_HEX_LEN    32u
#define BAJI_PHOTO_BIND_TOKEN_MAX_LEN   32u
#define BAJI_PHOTO_BIND_URL_MAX_LEN     320u

#define BAJI_PHOTO_HTTP_HOST            "127.0.0.1"
#define BAJI_PHOTO_HTTP_PORT            8000u
#define BAJI_PHOTO_HTTP_IOT_ID          "baji-watch"
#define BAJI_PHOTO_HTTP_INDEX_URI       "/baji/list?iot_id="
#define BAJI_PHOTO_HTTP_DOWNLOAD_URI    "/baji/download?path="
#define BAJI_PHOTO_HTTP_TIMEOUT_MS      10000u
#ifndef BAJI_PHOTO_HTTP_CLOSE_WAIT_MS
#define BAJI_PHOTO_HTTP_CLOSE_WAIT_MS   (BAJI_PHOTO_HTTP_TIMEOUT_MS + 5000u)
#endif
#define BAJI_PHOTO_HTTP_MANIFEST_MAX    (16u * 1024u)
#define BAJI_PHOTO_HTTP_SIM_ID          0u
#define BAJI_PHOTO_HTTP_PDP_CID         1
#define BAJI_PHOTO_HTTP_APN             "APNTEST"
#define BAJI_PHOTO_HTTP_REG_TIMEOUT_S   120u
#ifndef BAJI_PHOTO_HTTP_RETRY_MAX
#define BAJI_PHOTO_HTTP_RETRY_MAX       3u
#endif
#ifndef BAJI_PHOTO_HTTP_MANIFEST_RETRY_MAX
#define BAJI_PHOTO_HTTP_MANIFEST_RETRY_MAX 2u
#endif
#ifndef BAJI_PHOTO_HTTP_RETRY_BACKOFF_MS
#define BAJI_PHOTO_HTTP_RETRY_BACKOFF_MS 1000u
#endif
#ifndef BAJI_PHOTO_NETWORK_WAIT_RETRY_S
#define BAJI_PHOTO_NETWORK_WAIT_RETRY_S  3u
#endif
#ifndef BAJI_PHOTO_NETWORK_WAIT_DEADLINE_S
#define BAJI_PHOTO_NETWORK_WAIT_DEADLINE_S 60u
#endif
#ifndef BAJI_PHOTO_HTTP_REG_RETRY_MAX
#define BAJI_PHOTO_HTTP_REG_RETRY_MAX   3u
#endif
#ifndef BAJI_PHOTO_HTTP_DATACALL_RETRY_MAX
#define BAJI_PHOTO_HTTP_DATACALL_RETRY_MAX 2u
#endif
#ifndef BAJI_PHOTO_HTTP_DATACALL_READY_WAIT_MS
#define BAJI_PHOTO_HTTP_DATACALL_READY_WAIT_MS 10000u
#endif
#ifndef BAJI_PHOTO_HTTP_DATACALL_POLL_MS
#define BAJI_PHOTO_HTTP_DATACALL_POLL_MS 500u
#endif

#define BAJI_FLASH_LFS_BASE             0x010000u
#define BAJI_FLASH_LFS_TOTAL            0x7F0000u
#define BAJI_FLASH_LFS_BLOCK            4096u
#define BAJI_FLASH_LFS_READ             256u
#define BAJI_FLASH_LFS_PROG             256u

#define BAJI_PHOTO_STORE_DIR            "/flash/baji"
#define BAJI_PHOTO_STORE_PHOTO_DIR      "/flash/baji/photos"
#define BAJI_PHOTO_STORE_GIF_DIR        "/flash/baji/gifs"
#define BAJI_PHOTO_STORE_JPEG_DIR       "/flash/baji/jpeg"
#define BAJI_PHOTO_STORE_PNG_DIR        "/flash/baji/png"
#define BAJI_PHOTO_STORE_TMP_DIR        "/flash/baji/tmp"
#define BAJI_PHOTO_INDEX_FILE           "/flash/baji/index.json"
#define BAJI_PHOTO_INDEX_TMP_FILE       "/flash/baji/tmp/index.json.tmp"
#define BAJI_PHOTO_INDEX_BACKUP_FILE    "/flash/baji/index.json.bak"
#define BAJI_PHOTO_DELETE_JOURNAL_FILE  "/flash/baji/delete_pending.json"
#define BAJI_PHOTO_DELETE_JOURNAL_TMP_FILE "/flash/baji/tmp/delete_pending.json.tmp"
#define BAJI_PHOTO_META_FILE            "/flash/baji/meta.json"
#define BAJI_PHOTO_TASK_STATE_FILE      "/flash/baji/task_state.json"
#define BAJI_PHOTO_PENDING_REPLY_FILE   "/flash/baji/pending_reply.json"

#define BAJI_PHOTO_SYNC_TASK_STACK      8192u
#define BAJI_PHOTO_SYNC_TASK_PRIO       4u
#ifndef BAJI_PHOTO_DELETE_TASK_STACK
#define BAJI_PHOTO_DELETE_TASK_STACK    BAJI_PHOTO_SYNC_TASK_STACK
#endif
#ifndef BAJI_PHOTO_DELETE_TASK_PRIO
#define BAJI_PHOTO_DELETE_TASK_PRIO     BAJI_PHOTO_SYNC_TASK_PRIO
#endif
#ifndef BAJI_PHOTO_SLIDESHOW_INTERVAL_MS
#define BAJI_PHOTO_SLIDESHOW_INTERVAL_MS 5000u
#endif
#ifndef BAJI_PHOTO_CONTROLS_HIDE_MS
#define BAJI_PHOTO_CONTROLS_HIDE_MS     6500u
#endif
#define BAJI_PHOTO_ALLOW_AUTO_FORMAT    0

#endif
