ECAPI_HOST_DIRS := $(KERNELDIR)/ecapi

CFLAGS_INC += -I $(ECAPI_HOST_DIRS)
CFLAGS_INC += -I $(ECAPI_HOST_DIRS)/PLAT/prebuild/PLAT/inc
CFLAGS_INC += -I $(ECAPI_HOST_DIRS)/PLAT/driver/chip/ec7xx/ap/inc
CFLAGS_INC += -I $(ECAPI_HOST_DIRS)/PLAT/driver/chip/ec7xx/ap/inc_cmsis
CFLAGS_INC += -I $(ECAPI_HOST_DIRS)/PLAT/device/target/board/common/ARMCM3/inc
CFLAGS_INC += -I $(ECAPI_HOST_DIRS)/PLAT/device/target/board/ec7xx_0h00/ap/inc

CFLAGS += -DconfigUSE_NEWLIB_REENTRANT=1