__asm__(
    ".section .rodata\n"
    ".balign 4\n"
    ".global g_demo_mp3_because_mp3_start\n"
    ".global g_demo_mp3_because_mp3_end\n"
    ".global g_demo_mp3_because_cover_start\n"
    ".global g_demo_mp3_because_cover_end\n"
    ".global g_salary_coin_mp3_start\n"
    ".global g_salary_coin_mp3_end\n"
    "g_demo_mp3_because_mp3_start:\n"
    ".incbin \"../examples/L_CT4IT02_1698W/demo/src/demo_mp3/because of you_-12dB.mp3\"\n"
    "g_demo_mp3_because_mp3_end:\n"
    ".balign 4\n"
    "g_demo_mp3_because_cover_start:\n"
    ".incbin \"../examples/L_CT4IT02_1698W/demo/src/demo_mp3/because_of_you_cover_360x360.rgb565\"\n"
    "g_demo_mp3_because_cover_end:\n"
    ".balign 4\n"
    "g_salary_coin_mp3_start:\n"
    ".incbin \"../examples/L_CT4IT02_1698W/demo/src/demo_salary_calculator/coin_burst_44k.mp3\"\n"
    "g_salary_coin_mp3_end:\n"
    ".balign 4\n"
);
